### ISSUE TITLE
jq -r-f not found

### ISSUE THREAD

**Issue by ChampiYann** [reegnz/jq-zsh-plugin#11]
As mentioned in #9 I have a bug while using the plugin that looks to be only esthetical.
At the top of the REPL window I sometime get an error message, and sometime I don't see the error message because it gets covered up by a line of `0/0` (https://github.com/reegnz/jq-zsh-plugin/issues/9#issuecomment-968082632)

![zsh-jq-bug](https://user-images.githubusercontent.com/28050794/142822881-7580aebd-87b9-42c7-a9c2-4b3c71834f82.PNG)

I haven't noticed any issues with functionality.
My suspicion is that this has to do something with the fact that I load jq as a zsh plugin with this snippet:
```shell
zinit ice as"program" from"gh-r" bpick"*linux64*" mv"jq-* -> jq"
zinit load stedolan/jq
```

**Comment by jochenwierum** [comment]
I'm experiencing the same problem. I can reproduce it by calling `bin/jq-paths` directly.

Changing the first line of jq-paths from

```shell
#!/usr/bin/env jq -r -f
```

to

```shell
#!/usr/bin/env -S jq -r -f
```

solves the problem for me.
