### ISSUE TITLE
Suggest out put the query result, not the query-str

### ISSUE THREAD

**Issue by bigbuger** [reegnz/jq-zsh-plugin#12]
That is not sense to return the query-str, which is the default action by print-query.
I change it to print query result:

query=$(eval "$FZF_JQ_REPL_COMMAND" |
  fzf \
    --preview "jq --color-output ${JQ_REPL_ARGS:-} {q} \"$input\"" \
    --preview-window="down:90%" \
    --height="99%" \
    --query="." \
    --bind "tab:replace-query,return:print-query" \
    --bind "alt-up:preview-page-up,alt-down:preview-page-down" \
    --bind "ctrl-r:reload${fzf_notation}${FZF_JQ_REPL_COMMAND}${fzf_notation}+refresh-preview"
)
jq --color-output ${JQ_REPL_ARGS:-} $query "$input"

**Comment by bigbuger** [comment]
oh, i make a misstake about how to use

**Comment by reegnz** [comment]
Yupp, idea of this REPL is to find out what jq query to use to get a projection of the data, not the output itself, as you'd use the query with different data inputs later on.
