### ISSUE TITLE
Error when echoing out the jq-complete

### ISSUE THREAD

**Issue by barslmn** [reegnz/jq-zsh-plugin#16]
https://asciinema.org/a/kGPMXac3Hkg6u6JX8xm2Zh2SG

When I try to call jq-complete on an echo command I got the above errors. It works fine when catting from a file.
I installed over oh-my-zsh following the  #7   .

**Comment by reegnz** [comment]
you're not supposed to call `jq-complete` directly from the shell, it's containing line-editor functionality, and is only to be used as a line editor. The docs mention `jq-repl`.
Use `jq-repl` instead, that's inteded for direct shell invocations.
