### ISSUE TITLE
jq-repl fzf not found

### ISSUE THREAD

**Issue by arifmahmudrana** [reegnz/jq-zsh-plugin#19]
When pressing `alt + j` it shows `jq-repl: 36: fzf: not found`
![image](https://user-images.githubusercontent.com/2046796/214779500-a1025671-b12a-4ee5-9979-e91c90ea4a8f.png)

**Comment by arifmahmudrana** [comment]
I installed `fzf` now the message is `unknown action refresh preview`

**Comment by reegnz** [comment]
The `fzf` flag we're using got released in fzf 0.22.0 (which is a 2,5 year old release), so you need a version that's more recent. That's just the way is. 🤷‍♂️  You can check what version your distro provides over here: https://repology.org/project/fzf/versions

In case your distro does not provide a recent-enough fzf version, try the manual install either by downloading a binary from the github releases and putting it on your `PATH`, or cloning the git repo and building it from source: https://github.com/junegunn/fzf#using-git
