### ISSUE TITLE
jid (existing alternative)

### ISSUE THREAD

**Issue by brandonkal** [reegnz/jq-zsh-plugin#2]
This basically looks like [jid](https://github.com/simeji/jid). Pointing you there in case you haven't seen it.

https://github.com/simeji/jid

**Comment by reegnz** [comment]
I'm already aware of jid, but:
1. I want to keep the query and use it with jq in my scripts
2. it's much harder to use jid as a zsh line editor
2. I already use jq and fzf, and don't want to introduce an additional dependency

So yeah, `basically` is right, but practically it's a very different solution to what I needed.

**Comment by reegnz** [comment]
Some example where compatibility suffers: https://github.com/simeji/jid/issues/33

**Comment by reegnz** [comment]
I might look into using https://github.com/fiatjaf/jiq since that is actually using jq in the background. Although my 3rd point is still violated in that case (don't pull in additional dependencies).
