### ISSUE TITLE
__get_query:5: command not found: jq-repl

### ISSUE THREAD

**Issue by henrikno** [reegnz/jq-zsh-plugin#23]
I followed the instructions to add to oh-my-zsh, but got this error when doing alt+j.
`__get_query:5: command not found: jq-repl`

I fixed it by adding the bin dir to PATH
`export PATH="$PATH:/Users/me/.oh-my-zsh/custom/plugins/jq/bin"`

But am I supposed to do that manually? If so, could it be added to the installation instructions?

**Comment by reegnz** [comment]
I've had other people using the plugin with oh-my-zsh successfully. The plugin already adds the bin folder to the PATH:
https://github.com/reegnz/jq-zsh-plugin/blob/a5b404a8de5c0ef426f9bb4acbb31778862e2b18/jq.plugin.zsh#L41

Closing as user-error.
