### ISSUE TITLE
How to install without a plugin manager?

### ISSUE THREAD

**Issue by ehaughee** [reegnz/jq-zsh-plugin#3]
I don't use a plugin manager for my ZSH setup.  I tried cloning and sourcing the .zsh file but the keybindings don't work.  Any suggestions?

**Comment by reegnz** [comment]
Which OS + terminal emulator are you using?

**Comment by ehaughee** [comment]
macOS Catalina + iTerm2 but I also run ZSH on [Amazon Linux 2](https://aws.amazon.com/amazon-linux-2/) distros via SSH and often use tmux if that is relevant.

**Comment by reegnz** [comment]
For macos and iterm2 you need to remap the meta key so that you can send the proper escape sequence.

See the following blog post as an example:
https://thinkingeek.com/2012/11/17/mac-os-x-iterm-meta-key/

**Comment by jasmeet2dhiman** [comment]
It would be nice to have something default for Mac

**Comment by reegnz** [comment]
What kind of default do you have in mind?
There's already a default that's meta+j.
