### ISSUE TITLE
Thank you! + Add fish port to readme?

### ISSUE THREAD

**Issue by rmartine-ias** [reegnz/jq-zsh-plugin#30]
Hey, thanks for making this, it's super neat! I remembered someone mentioning this was possible, but whatever snippet they had was significantly less fully-featured. The tab completion is so nice.

I ported this to the fish shell (not necessarily very well, but it works), if you wanted to link that in your README: https://github.com/rmartine-ias/jq-fish-plugin

**Comment by reegnz** [comment]
You're awesome! Added a link to your fork.
