### ISSUE TITLE
Will there be further optimization?

### ISSUE THREAD

**Issue by lunrenyi** [reegnz/jq-zsh-plugin#36]
Hi, will this plugin be further optimized in the future, for example
- Instant Results: See the output of your jq filter in real-time.
- Error Handling: Encounter a syntax error? display the error message and the results of the closest valid filter.

[discussions: jq and fzf](https://github.com/jqlang/jq/discussions/3155)
<img width="874" alt="image" src="https://github.com/user-attachments/assets/addb0535-4ddd-463a-934e-761637355e49">

**Comment by reegnz** [comment]
> will this plugin be further optimized in the future

Not sure if there's anything to optimize really.
One of my project goals is to keep complexity low. We're talking about an integration of jq, fzf and zsh, it's a project written in shell scripts, so don't want it to explode in complexity. If someone wants anything more complicated they should write it in a different language that's not shell scripts.

> Instant Results: See the output of your jq filter in real-time.
The jq filter is already evaluated in real-time and is instant (as soon as the piped-in command finishes) so not sure about that question. What more do you want there?

> Error Handling: Encounter a syntax error? display the error message and the results of the closest valid filter.

We already display the error message when the syntax is wrong.
Regarding suggestions, I have to circle back to the design goal of keeping complexity low, suggestion logic is are out-of-scope for this particular project.
