### ISSUE TITLE
Using this plugin with iTerm2

### ISSUE THREAD

**Issue by johnhamelink** [reegnz/jq-zsh-plugin#4]
Hi there,

I just wanted to leave a note to let you know how to use this plugin with Iterm2:

1. `Cmd + ,` to enter preferences
2. Go to Profiles, select your profile from the pane on the left hand side, then go to the `keys` tab.
3. Set `Left Option (⌥) Key` to `Esc+`

If you don't set things this way, `alt+j` will create a `∆` symbol.

That's all!

**Comment by reegnz** [comment]
Wanna do a PR for the README?

**Comment by darwinz** [comment]
I tried the exact steps here in iTerm2, but I still get a `∆` symbol.  I still can't get this to work in iTerm2.  Are there any other steps that I might be missing?

**Comment by reegnz** [comment]
TBQH that's probably an issue with either your keyboard, or your iterm config.
I think stackoverflow might be a better help on that: https://stackoverflow.com/questions/196357/making-iterm-to-translate-meta-key-in-the-same-way-as-in-other-oses

**Comment by reegnz** [comment]
An alternative is to map it not to `meta + j` but to something else, like `ctrl + j`:

```sh
bindkey `^j` jq-complete
```

**Comment by darwinz** [comment]
> An alternative is to map it not to `meta + j` but to something else, like `ctrl + j`:
> 
> ```shell
> bindkey `^j` jq-complete
> ```

Thanks, that works.  Not sure why `meta + j` doesn't work for me.  Probably something in my config, like you mentioned.
