### ISSUE TITLE
Support completion of json keys

### ISSUE THREAD

**Issue by alahijani** [reegnz/jq-zsh-plugin#6]
One could implement some basic key completion using `jq -r ... | keys`. 

I can submit a PR if you are interested.

**Comment by reegnz** [comment]
Thank you for the suggestion! I decided to implement the feature somewhat differently than you did.

**Comment by alahijani** [comment]
I actually like your solution better! 
There may still be a use case for triggering a reload as a separate feature, but I need to further develop that idea.
