### ISSUE TITLE
how can i use it with oh my zsh

### ISSUE THREAD

**Issue by linhaoi1997** [reegnz/jq-zsh-plugin#7]

**Comment by reegnz** [comment]
https://github.com/ohmyzsh/ohmyzsh#custom-plugins-and-themes

Some detailed instructions can be found in this blog post: https://blog.larsbehrenberg.com/how-to-install-custom-plugins-and-themes-with-oh-my-zsh

I do suggest starting to go into a plugin manager direction instead and start using antigen or zplug, it's much cleaner than configuring oh-my-zsh (and they're compatible with oh-my-zsh plugins).

**Comment by linhaoi1997** [comment]
![image](https://user-images.githubusercontent.com/51370091/128683138-9cdd41d0-2130-4db4-b3f1-d7502ae3e97b.png)
i downloads the project to `~/.oh-my-zsh/custom/plugins/jq-zsh-plugin`
but zsh raise error jq-zsh-plugin not found

i change  `jq.plugin.zsh` to `jq-zsh-plugin.plugin.zsh`
zsh does not raise error anymore
but when i use some commands generate json
nothing happened
![image](https://user-images.githubusercontent.com/51370091/128683626-4bc487e5-183f-4b2a-a4ba-11b190b30f94.png)
is there someway i can actively use this plug

**Comment by reegnz** [comment]
instead of executing the command with 'return', you need to use the binding, which is meta+j by default. 
You usually map the meta key to alt, but that depends on the terminal emulator you are using.

**Comment by linhaoi1997** [comment]
thanks ,it worked !!
